//#line 2 "/home/art/Workspace/ROS/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the art_arduino package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __art_arduino__PIDCONFIG_H__
#define __art_arduino__PIDCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace art_arduino
{
  class PIDConfigStatics;
  
  class PIDConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(PIDConfig &config, const PIDConfig &max, const PIDConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const PIDConfig &config1, const PIDConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, PIDConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const PIDConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PIDConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const PIDConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T PIDConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (PIDConfig::* field);

      virtual void clamp(PIDConfig &config, const PIDConfig &max, const PIDConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const PIDConfig &config1, const PIDConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, PIDConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const PIDConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, PIDConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const PIDConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 8 "../cfg/pid.cfg"
      double proll;
//#line 9 "../cfg/pid.cfg"
      double iroll;
//#line 10 "../cfg/pid.cfg"
      double droll;
//#line 11 "../cfg/pid.cfg"
      double ppitch;
//#line 12 "../cfg/pid.cfg"
      double ipitch;
//#line 13 "../cfg/pid.cfg"
      double dpitch;
//#line 14 "../cfg/pid.cfg"
      double pyaw;
//#line 15 "../cfg/pid.cfg"
      double iyaw;
//#line 16 "../cfg/pid.cfg"
      double dyaw;
//#line 17 "../cfg/pid.cfg"
      double paltitude;
//#line 18 "../cfg/pid.cfg"
      double ialtitude;
//#line 19 "../cfg/pid.cfg"
      double daltitude;
//#line 138 "/home/art/Workspace/ROS/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("PIDConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const PIDConfig &__max__ = __getMax__();
      const PIDConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const PIDConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const PIDConfig &__getDefault__();
    static const PIDConfig &__getMax__();
    static const PIDConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const PIDConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void PIDConfig::ParamDescription<std::string>::clamp(PIDConfig &config, const PIDConfig &max, const PIDConfig &min) const
  {
    return;
  }

  class PIDConfigStatics
  {
    friend class PIDConfig;
    
    PIDConfigStatics()
    {
//#line 8 "../cfg/pid.cfg"
      __min__.proll = -10.0;
//#line 8 "../cfg/pid.cfg"
      __max__.proll = 10.0;
//#line 8 "../cfg/pid.cfg"
      __default__.proll = 0.0;
//#line 8 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("proll", "double", 0, "", "", &PIDConfig::proll)));
//#line 9 "../cfg/pid.cfg"
      __min__.iroll = -10.0;
//#line 9 "../cfg/pid.cfg"
      __max__.iroll = 10.0;
//#line 9 "../cfg/pid.cfg"
      __default__.iroll = 0.0;
//#line 9 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("iroll", "double", 0, "", "", &PIDConfig::iroll)));
//#line 10 "../cfg/pid.cfg"
      __min__.droll = -10.0;
//#line 10 "../cfg/pid.cfg"
      __max__.droll = 10.0;
//#line 10 "../cfg/pid.cfg"
      __default__.droll = 0.0;
//#line 10 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("droll", "double", 0, "", "", &PIDConfig::droll)));
//#line 11 "../cfg/pid.cfg"
      __min__.ppitch = -10.0;
//#line 11 "../cfg/pid.cfg"
      __max__.ppitch = 10.0;
//#line 11 "../cfg/pid.cfg"
      __default__.ppitch = 0.0;
//#line 11 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("ppitch", "double", 0, "", "", &PIDConfig::ppitch)));
//#line 12 "../cfg/pid.cfg"
      __min__.ipitch = -10.0;
//#line 12 "../cfg/pid.cfg"
      __max__.ipitch = 10.0;
//#line 12 "../cfg/pid.cfg"
      __default__.ipitch = 0.0;
//#line 12 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("ipitch", "double", 0, "", "", &PIDConfig::ipitch)));
//#line 13 "../cfg/pid.cfg"
      __min__.dpitch = -10.0;
//#line 13 "../cfg/pid.cfg"
      __max__.dpitch = 10.0;
//#line 13 "../cfg/pid.cfg"
      __default__.dpitch = 0.0;
//#line 13 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("dpitch", "double", 0, "", "", &PIDConfig::dpitch)));
//#line 14 "../cfg/pid.cfg"
      __min__.pyaw = -10.0;
//#line 14 "../cfg/pid.cfg"
      __max__.pyaw = 10.0;
//#line 14 "../cfg/pid.cfg"
      __default__.pyaw = 0.0;
//#line 14 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("pyaw", "double", 0, "", "", &PIDConfig::pyaw)));
//#line 15 "../cfg/pid.cfg"
      __min__.iyaw = -10.0;
//#line 15 "../cfg/pid.cfg"
      __max__.iyaw = 10.0;
//#line 15 "../cfg/pid.cfg"
      __default__.iyaw = 0.0;
//#line 15 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("iyaw", "double", 0, "", "", &PIDConfig::iyaw)));
//#line 16 "../cfg/pid.cfg"
      __min__.dyaw = -10.0;
//#line 16 "../cfg/pid.cfg"
      __max__.dyaw = 10.0;
//#line 16 "../cfg/pid.cfg"
      __default__.dyaw = 0.0;
//#line 16 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("dyaw", "double", 0, "", "", &PIDConfig::dyaw)));
//#line 17 "../cfg/pid.cfg"
      __min__.paltitude = -10.0;
//#line 17 "../cfg/pid.cfg"
      __max__.paltitude = 10.0;
//#line 17 "../cfg/pid.cfg"
      __default__.paltitude = 0.0;
//#line 17 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("paltitude", "double", 0, "", "", &PIDConfig::paltitude)));
//#line 18 "../cfg/pid.cfg"
      __min__.ialtitude = -10.0;
//#line 18 "../cfg/pid.cfg"
      __max__.ialtitude = 10.0;
//#line 18 "../cfg/pid.cfg"
      __default__.ialtitude = 0.0;
//#line 18 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("ialtitude", "double", 0, "", "", &PIDConfig::ialtitude)));
//#line 19 "../cfg/pid.cfg"
      __min__.daltitude = -10.0;
//#line 19 "../cfg/pid.cfg"
      __max__.daltitude = 10.0;
//#line 19 "../cfg/pid.cfg"
      __default__.daltitude = 0.0;
//#line 19 "../cfg/pid.cfg"
      __param_descriptions__.push_back(PIDConfig::AbstractParamDescriptionConstPtr(new PIDConfig::ParamDescription<double>("daltitude", "double", 0, "", "", &PIDConfig::daltitude)));
//#line 239 "/home/art/Workspace/ROS/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<PIDConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<PIDConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    PIDConfig __max__;
    PIDConfig __min__;
    PIDConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const PIDConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static PIDConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &PIDConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const PIDConfig &PIDConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const PIDConfig &PIDConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const PIDConfig &PIDConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<PIDConfig::AbstractParamDescriptionConstPtr> &PIDConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const PIDConfigStatics *PIDConfig::__get_statics__()
  {
    const static PIDConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = PIDConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __PIDRECONFIGURATOR_H__
