(cl:defpackage hector_nav_msgs-srv
  (:use )
  (:export
   "GETSEARCHPOSITION"
   "<GETSEARCHPOSITION-REQUEST>"
   "GETSEARCHPOSITION-REQUEST"
   "<GETSEARCHPOSITION-RESPONSE>"
   "GETSEARCHPOSITION-RESPONSE"
   "GETDISTANCETOOBSTACLE"
   "<GETDISTANCETOOBSTACLE-REQUEST>"
   "GETDISTANCETOOBSTACLE-REQUEST"
   "<GETDISTANCETOOBSTACLE-RESPONSE>"
   "GETDISTANCETOOBSTACLE-RESPONSE"
   "GETROBOTTRAJECTORY"
   "<GETROBOTTRAJECTORY-REQUEST>"
   "GETROBOTTRAJECTORY-REQUEST"
   "<GETROBOTTRAJECTORY-RESPONSE>"
   "GETROBOTTRAJECTORY-RESPONSE"
  ))

